// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Panyebar.Infrastructure.Persistence;

#nullable disable

namespace Panyebar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PanyebarDbContext))]
    [Migration("20260911003707_ConfigureCommunityWorkDays")]
    partial class ConfigureCommunityWorkDays
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("SuministroNisSequence", "dbo");

            modelBuilder.Entity("Panyebar.Domain.Entities.AdministracionComite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdministracionesComite");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.AplicacionPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ObligacionId")
                        .HasColumnType("int");

                    b.Property<int>("PagoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObligacionId");

                    b.HasIndex("PagoId", "ObligacionId")
                        .IsUnique();

                    b.ToTable("AplicacionesPago");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioAdministrativoId")
                        .HasColumnType("int");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAdministrativoId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFinVigencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioVigencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Periodicidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cuotas");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Egreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioAdministrativoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAdministrativoId");

                    b.ToTable("Egresos");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.IntegranteAdministracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministracionComiteId")
                        .HasColumnType("int");

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("AdministracionComiteId", "PersonaId", "CargoId")
                        .IsUnique();

                    b.ToTable("IntegrantesAdministracion");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Jornada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly?>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<decimal?>("MontoIncumplimiento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Jornadas", t =>
                        {
                            t.HasCheckConstraint("CK_Jornadas_EstadoValido", "[Estado] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_Jornadas_HorarioValido", "[HoraInicio] IS NULL OR [HoraFin] IS NULL OR [HoraFin] > [HoraInicio]");

                            t.HasCheckConstraint("CK_Jornadas_MontoIncumplimientoPositivo", "[MontoIncumplimiento] IS NULL OR [MontoIncumplimiento] > 0");
                        });
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Obligacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CuotaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Origen")
                        .HasColumnType("int");

                    b.Property<string>("Periodo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int?>("SuministroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId", "Estado")
                        .HasDatabaseName("IX_Obligaciones_PersonaId_Estado");

                    b.HasIndex("SuministroId", "Estado")
                        .HasDatabaseName("IX_Obligaciones_SuministroId_Estado");

                    b.HasIndex("CuotaId", "SuministroId", "Periodo")
                        .IsUnique()
                        .HasDatabaseName("IX_Obligaciones_CuotaId_SuministroId_Periodo")
                        .HasFilter("[CuotaId] IS NOT NULL AND [SuministroId] IS NOT NULL AND [Periodo] IS NOT NULL AND [Estado] <> 3");

                    b.ToTable("Obligaciones", t =>
                        {
                            t.HasCheckConstraint("CK_Obligaciones_TitularXor", "([SuministroId] IS NOT NULL AND [PersonaId] IS NULL) OR ([SuministroId] IS NULL AND [PersonaId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.ObligacionJornada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ObligacionId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipacionJornadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObligacionId")
                        .IsUnique()
                        .HasDatabaseName("IX_ObligacionesJornada_ObligacionId");

                    b.HasIndex("ParticipacionJornadaId")
                        .IsUnique()
                        .HasDatabaseName("IX_ObligacionesJornada_ParticipacionJornadaId");

                    b.ToTable("ObligacionesJornada");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioAdministrativoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAdministrativoId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.ParticipacionJornada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JornadaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Resultado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("JornadaId", "PersonaId")
                        .IsUnique();

                    b.ToTable("ParticipacionesJornada", t =>
                        {
                            t.HasCheckConstraint("CK_ParticipacionesJornada_ResultadoValido", "[Resultado] IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DireccionReferencia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Identificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasFilter("[Identificacion] IS NOT NULL");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.PersonaSuministro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("SuministroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("SuministroId")
                        .IsUnique()
                        .HasFilter("[Estado] = 1");

                    b.ToTable("PersonaSuministros");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.ProcesoSuministro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SuministroId")
                        .HasColumnType("int");

                    b.Property<int>("TipoProceso")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioAdministrativoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAdministrativoId");

                    b.HasIndex("SuministroId", "Fecha");

                    b.ToTable("ProcesosSuministro");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.ProgramacionAbastecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("ProgramacionesAbastecimiento");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.RolPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId", "PermisoId")
                        .IsUnique();

                    b.ToTable("RolPermisos");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Sectores");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.SolicitudNuevoServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionReferencia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PersonaSolicitanteId")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<int?>("SuministroId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResolucionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaSolicitanteId");

                    b.HasIndex("SectorId");

                    b.HasIndex("SuministroId");

                    b.HasIndex("UsuarioResolucionId");

                    b.HasIndex("Estado", "FechaSolicitud");

                    b.ToTable("SolicitudesNuevoServicio");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Suministro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoQrToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DireccionReferencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nis")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoQrToken")
                        .IsUnique();

                    b.HasIndex("Nis")
                        .IsUnique();

                    b.HasIndex("SectorId");

                    b.ToTable("Suministros");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.UsuarioAdministrativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("UsuariosAdministrativos");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioAdministrativoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioAdministrativoId", "RolId")
                        .IsUnique();

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.AplicacionPago", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.Obligacion", "Obligacion")
                        .WithMany()
                        .HasForeignKey("ObligacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Panyebar.Domain.Entities.Pago", "Pago")
                        .WithMany()
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obligacion");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.UsuarioAdministrativo", "UsuarioAdministrativo")
                        .WithMany()
                        .HasForeignKey("UsuarioAdministrativoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioAdministrativo");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Egreso", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.UsuarioAdministrativo", null)
                        .WithMany()
                        .HasForeignKey("UsuarioAdministrativoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.IntegranteAdministracion", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.AdministracionComite", "AdministracionComite")
                        .WithMany()
                        .HasForeignKey("AdministracionComiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Panyebar.Domain.Entities.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Panyebar.Domain.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdministracionComite");

                    b.Navigation("Cargo");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Obligacion", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.Cuota", "Cuota")
                        .WithMany()
                        .HasForeignKey("CuotaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Panyebar.Domain.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Panyebar.Domain.Entities.Suministro", "Suministro")
                        .WithMany()
                        .HasForeignKey("SuministroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cuota");

                    b.Navigation("Persona");

                    b.Navigation("Suministro");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.ObligacionJornada", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.Obligacion", "Obligacion")
                        .WithOne()
                        .HasForeignKey("Panyebar.Domain.Entities.ObligacionJornada", "ObligacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Panyebar.Domain.Entities.ParticipacionJornada", "ParticipacionJornada")
                        .WithOne()
                        .HasForeignKey("Panyebar.Domain.Entities.ObligacionJornada", "ParticipacionJornadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obligacion");

                    b.Navigation("ParticipacionJornada");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Pago", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.UsuarioAdministrativo", null)
                        .WithMany()
                        .HasForeignKey("UsuarioAdministrativoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.ParticipacionJornada", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.Jornada", "Jornada")
                        .WithMany()
                        .HasForeignKey("JornadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Panyebar.Domain.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jornada");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.PersonaSuministro", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Panyebar.Domain.Entities.Suministro", "Suministro")
                        .WithMany()
                        .HasForeignKey("SuministroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Suministro");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.ProcesoSuministro", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.Suministro", "Suministro")
                        .WithMany()
                        .HasForeignKey("SuministroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Panyebar.Domain.Entities.UsuarioAdministrativo", "UsuarioAdministrativo")
                        .WithMany()
                        .HasForeignKey("UsuarioAdministrativoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Suministro");

                    b.Navigation("UsuarioAdministrativo");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.ProgramacionAbastecimiento", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.RolPermiso", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Panyebar.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.SolicitudNuevoServicio", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.Persona", "PersonaSolicitante")
                        .WithMany()
                        .HasForeignKey("PersonaSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Panyebar.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Panyebar.Domain.Entities.Suministro", "Suministro")
                        .WithMany()
                        .HasForeignKey("SuministroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Panyebar.Domain.Entities.UsuarioAdministrativo", "UsuarioResolucion")
                        .WithMany()
                        .HasForeignKey("UsuarioResolucionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PersonaSolicitante");

                    b.Navigation("Sector");

                    b.Navigation("Suministro");

                    b.Navigation("UsuarioResolucion");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.Suministro", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Panyebar.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("Panyebar.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Panyebar.Domain.Entities.UsuarioAdministrativo", "UsuarioAdministrativo")
                        .WithMany()
                        .HasForeignKey("UsuarioAdministrativoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("UsuarioAdministrativo");
                });
#pragma warning restore 612, 618
        }
    }
}
